---
title: 'Rumsay, Chapter 3: Organizing quantitative data - Charts and graphs. [Ongoing
  - Lattice graphics]'
author: "Maurizio Murino"
date: "3 March 2016"
output: html_document
---
```{r setoption, cache=TRUE, warning=FALSE, message=FALSE, fig.width=12}
knitr::opts_chunk$set(cache=TRUE, warning=FALSE, message=FALSE, fig.width=12)
```

```{r, loadlattice}
library(lattice)
library(xtable)
```

### Exercise 1 - 3/3/'16

You lose information from the data when yu create a histogram. What information is lost?

__Solution:__

You do not know the actual value of the data anymore, but only the group where they fall into.

### Exercise 2 - 3/3/'16

Make a histogram from this dataset of test scores: 72, 79, 81, 80, 63, 62, 89, 90, 50, 78, 87, 97, 55, 69, 97, 87, 88, 99, 76, 78, 5, 77, 88, 90, 81. Would a pie chart be appropriated for this data?

```{r 2.1 dataload}
e2 <- c(72, 79, 81, 80, 63, 62, 89, 90, 50, 78, 87, 97, 55, 69, 97, 87, 88, 99, 76, 78, 65, 77, 88, 90, 81)
```
```{r 2.2 histogram, lattice}
histogram(~e2)
```
```{r 2.2 histogram, base}
histogram(e2)
```

